export enum Permissions {
    // SITE OWNER PERMISSIONS
    ADMINISTRATOR = 1 << 0,
    MANAGE_WEBSITE = 1 << 1,
    DELETE_ACCOUNTS = 1 << 2,

    // SITE ADMINISTRATOR PERMISSIONS
    MANAGE_ACCOUNTS = 1 << 3,

    // SITE MODERATOR PERMISSIONS
    MANAGE_USER_GROUPS = 1 << 4,
    MANAGE_MANGA = 1 << 5,

    // MANGA OWNER PERMISSIONS
    DELETE_MANGA = 1 << 6,
    CREATE_MANGA = 1 << 7,

    // MANGA EDITOR PERMISSIONS
    EDIT_COVER = 1 << 8,
    EDIT_PAGES = 1 << 9,
    EDIT_METADATA = 1 << 10,
}

export enum TokenType {
    SESSION,
    API
}